# --- QMIX specific parameters ---
seed : 0
run_name : "QMIX"
exp_name : "doudizhu"
# use epsilon greedy action selector
action_selector: "rlcard"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z
alg : "qmix"
runner: "rlcard"
batch_size_run: 16 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000
batch_size: 8
optimizer: 'adam'

t_max: 50100000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "rlcard"
agent: "card_rnn"
agent_output_type: q

learner: "rlcard"
mixer: "qmix"
mixing_embed_dim: 320
hypernet_embed: 64
lr: 0.001 # Learning rate for agents
td_lambda: 0.6 # 0.3 for 6h_vs_8z
q_lambda: False

# rnn layer normalization
use_layer_norm: False

# orthogonal init for DNN
use_orthogonal: False
gain: 0.01

# Priority experience replay
use_per: False
per_alpha: 0.6
per_beta: 0.4
return_priority: False

name: "qmix_env=8_adam_td_lambda"
